version: "3.18"

services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/code/static
    depends_on:
      api:
        condition: service_started
    links:
      - api


  api: &api
    container_name: api
    build:
      context: .
    tty: false
    volumes:
      - .:/code
    restart: on-failure
    links:
      - redis
      - db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python manage.py migrate --noinput & python3 manage.py collectstatic --noinput & gunicorn config.wsgi --access-logfile - --workers 3 --bind 0.0.0.0:8000"

  celery-worker:
    <<: *api
    container_name: celery-worker
    command: bash -c "python3 manage.py telegram_bot & python3 manage.py check_habits & celery -A config worker -l info"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    <<: *api
    container_name: celery-beat
    command: celery -A config beat -l info -S django
    depends_on:
      celery-worker:
        condition: service_started

