# Generated by Django 4.1.7 on 2023-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_execution',
            field=models.DateField(blank=True, null=True, verbose_name='последнее выполнение'),
        ),
    ]
